export const MAIN_IMAGE_DATA = [
  {
    id: 1,
    img: '/images/1.jpg',
    desc: '180개 머니 클래스, 1년 간 무제한 수강!',
    subDesc: '재테크/ 창업을 한번에!!',
    bg: '#6300D8',
  },
  {
    id: 2,
    img: '/images/2.jpg',
    desc: '클래스만 사도 IPAD 무료증정!',
    subDesc: '화난거 아니에요 물지 않아요',
    bg: '#00B8EA',
  },
  {
    id: 3,
    img: '/images/bb.png',
    desc: '하고싶은거 다 가능! top50 최대 97%',
    subDesc: '인기클래스! 눈으로 욕하는법 ',
    bg: 'black',
  },
  {
    id: 4,
    img: '/images/4.jpg',
    desc: '댓글만 작성해도 최대 20만원!',
    subDesc: '라벨이 뭐에요? 스티커요! 하...',
    bg: '#FF5A00',
  },
  {
    id: 5,
    img: '/images/5.jpg',
    desc: '집이 없어 불안하다면 지금 당장 클릭하세요',
    subDesc: '22년 집 마련해드릴게요!',
    bg: '#133337',
  },
  {
    id: 6,
    img: '/images/6.jpg',
    desc: '단 3개월 - 바로,  위코드에서 개발자가 되는데 필요한 시간',
    subDesc: '함께해서 위코드!',
    bg: '#806040',
  },
  {
    id: 7,
    img: '/images/7.jpg',
    desc: '하루 10분 습관 만들기! 100가지 루틴',
    subDesc: '2월한정 인기클래스들을 한번에 수강!',
    bg: '#007d8c',
  },
  {
    id: 8,
    img: '/images/8.jpg',
    desc: '단 3개월 - 바로,  위코드에서 개발자가 되는데 필요한 시간',
    subDesc: '함께해서 위코드!',
    bg: '#701718',
  },
  {
    id: 9,
    img: '/images/9.jpg',
    desc: '단 3개월 - 바로,  위코드에서 개발자가 되는데 필요한 시간',
    subDesc: '함께해서 위코드!',
    bg: '#d8a52f',
  },
  {
    id: 10,
    img: '/images/11.jpg',
    desc: '올바른 육아! 행복한 가족 만들기',
    subDesc: '행복한 가족이 올바른 아이를 키웁니다',
    bg: '#ff7f01',
  },
  {
    id: 10,
    img: '/images/12.jpg',
    desc: '오랫동안 간직 될 행복한 순간',
    subDesc: '사진 한장에 모든 기억을 아름답게',
    bg: '#ff7f01',
  },
];
