export const PRODUCT_DATA = [
  {
    id: 1,
    route_url: '/main',
    img_url: '/images/1.jpg',
    user_id: '안녕늘봄씨',
    class_title:
      '[:선물:2월특가] 취향을 담아 만드는 19권의 수제 노트, 안녕늘보씨의 북바인딩',
    class_heart: '5145',
    class_like: '99%',
    sale: '33%',
    price: '49,900',
    term: '5',
  },
  {
    id: 2,
    route_url: '/main',
    img_url: '/images/2.jpg',
    coupon: '3만원 쿠폰',
    user_id: '안녕늘봄씨',
    class_title:
      '[:선물:2월특가] 취향을 담아 만드는 19권의 수제 노트, 안녕늘보씨의 북바인딩',
    class_heart: '5145',
    class_like: '99%',
    sale: '33%',
    price: '49,900',
    term: '5',
  },
  {
    id: 3,
    route_url: '/main',
    img_url: '/images/bb.png',
    coupon: '3만원 쿠폰',
    user_id: '안녕늘봄씨',
    class_title:
      '[:선물:2월특가] 취향을 담아 만드는 19권의 수제 노트, 안녕늘보씨의 북바인딩',
    class_heart: '5145',
    class_like: '99%',
    sale: '33%',
    price: '49,900',
    term: '5',
  },
  {
    id: 4,
    route_url: '/main',
    img_url: '/images/4.jpg',
    coupon: '3만원 쿠폰',
    user_id: '안녕늘봄씨',
    class_title:
      '[:선물:2월특가] 취향을 담아 만드는 19권의 수제 노트, 안녕늘보씨의 북바인딩',
    class_heart: '5145',
    class_like: '99%',
    sale: '33%',
    price: '49,900',
    term: '5',
  },
  {
    id: 5,
    route_url: '/main',
    img_url: '/images/5.jpg',
    coupon: '3만원 쿠폰',
    user_id: '안녕늘봄씨',
    class_title:
      '[:선물:2월특가] 취향을 담아 만드는 19권의 수제 노트, 안녕늘보씨의 북바인딩',
    class_heart: '5145',
    class_like: '99%',
    sale: '33%',
    price: '49,900',
    term: '5',
  },
  {
    id: 6,
    route_url: '/main',
    img_url: '/images/6.jpg',
    coupon: '3만원 쿠폰',
    user_id: '안녕늘봄씨',
    class_title:
      '[:선물:2월특가] 취향을 담아 만드는 19권의 수제 노트, 안녕늘보씨의 북바인딩',
    class_heart: '5145',
    class_like: '99%',
    sale: '33%',
    price: '49,900',
    term: '5',
  },
];
